- name: install apache and php packages
  tags: apache,httpd,php,ubuntu,rocky
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start httpd (Rocky)
  tags: apache,httpd,rocky
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change e-mail for admin
  tags: apache,rocky,httpd,email
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin someonone@whatever.com
  when: ansible_distribution == "Rocky"
  notify: restart_apache

- name: copy default html file
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
