- name: install Mariadb Rocky
  tags: rocky,mariadb,db
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "Rocky"

- name: install Mariadb Ubuntu
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
